# Generated by Django 5.0.3 on 2024-03-26 07:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Что?')),
                ('place', models.CharField(max_length=150, verbose_name='Где?')),
                ('start_date', models.DateField(default=datetime.date(2024, 3, 26), verbose_name='Когда?')),
                ('time', models.TimeField(default=datetime.time(7, 4, 55, 113487), verbose_name='Во сколько?')),
                ('duration', models.DurationField(default='00:00:00', verbose_name='Выполнять чч:мм:сс')),
                ('period', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('in 2 days', 'каждые 2 дня'), ('in 3 days', 'каждые 3 дня'), ('in 4 days', 'каждые 4 дня'), ('in 5 days', 'каждые 5 дней'), ('in 6 days', 'каждые 6 дней')], default='daily', max_length=20, verbose_name='Как часто?')),
                ('is_nice', models.BooleanField(default=False, verbose_name='Приятная')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='good_habit', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Cоздатель привычки')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('id',),
            },
        ),
    ]
