# Generated by Django 5.0.3 on 2024-03-29 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 3, 29), verbose_name='Когда?'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(15, 4, 11, 983633), verbose_name='Во сколько?'),
        ),
    ]
